In [1]:
#importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
#read csv file

df = pd.read_csv("D:/Fraud Detection model project 2/Raw_dataset/financial_fraud_detection_dataset.csv")

In [3]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Amount,Merchant_Category,Payment_Method,Device_Type,Location,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Suspicious_Keyword,Fraudulent,Unnamed: 14
0,T100000,CUST3252,04-10-2023 07:45,37.54,Travel,PayPal,POS,Bengaluru,0,94,417.40,1492,No,0,NaN
1,T100001,CUST1630,26-09-2023 08:29,240.81,Utilities,PayPal,Mobile,Bengaluru,0,76,335.47,66,No,0,NaN
2,T100002,CUST7852,18-07-2023 15:54,105.34,Entertainment,Debit Card,Mobile,Bengaluru,0,60,432.03,216,No,0,NaN
3,T100003,CUST4892,16-10-2023 17:10,73.04,Utilities,NetBanking,Desktop,Kolkata,0,68,488.30,449,No,0,NaN
4,T100004,CUST8831,09-09-2023 00:46,13.57,Utilities,Credit Card,Desktop,Bengaluru,0,57,437.03,754,No,0,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Transaction_ID         5000 non-null   str
 1   Customer_ID            5000 non-null   str
 2   Transaction_Date       5000 non-null   str
 3   Transaction_Amount     5000 non-null   float64
 4   Merchant_Category      5000 non-null   str
 5   Payment_Method         5000 non-null   str
 6   Device_Type            5000 non-null   str
 7   Location               5000 non-null   str
 8   Is_International       5000 non-null   int64
 9   Previous_Transactions  5000 non-null   int64
 10  Average_Spend          5000 non-null   float64
 11  Account_Age_Days       5000 non-null   int64
 12  Suspicious_Keyword     5000 non-null   str
 13  Fraudulent             5000 non-null   int64
 14  Unnamed: 14            0 non-null      float64
dtypes: float64(3), int64(4), str(8)
memory usage: 883.7 KB

In [5]:
df.shape

(5000, 15)

In [6]:
df.describe()

,Transaction_Amount,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Fraudulent,Unnamed: 14
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,0.0
mean,79.180664,0.088200,99.414000,258.377132,1011.158200,0.096400,NaN
std,78.964045,0.283614,57.022968,140.230639,568.633834,0.295169,NaN
min,0.000000,0.000000,1.000000,10.010000,30.000000,0.000000,NaN
25%,22.365000,0.000000,50.000000,138.772500,530.000000,0.000000,NaN
50%,55.455000,0.000000,100.000000,261.810000,1012.500000,0.000000,NaN
75%,110.297500,0.000000,148.000000,378.525000,1496.000000,0.000000,NaN
max,653.800000,1.000000,199.000000,499.990000,1999.000000,1.000000,NaN

In [7]:
# missing values in the dataset
df.isnull().sum()

Transaction_ID              0
Customer_ID                 0
Transaction_Date            0
Transaction_Amount          0
Merchant_Category           0
Payment_Method              0
Device_Type                 0
Location                    0
Is_International            0
Previous_Transactions       0
Average_Spend               0
Account_Age_Days            0
Suspicious_Keyword          0
Fraudulent                  0
Unnamed: 14              5000
dtype: int64

In [8]:
# missing percentage in the dataset
missing_percentage = df.isnull().sum() / len(df) * 100
print(missing_percentage)

Transaction_ID             0.0
Customer_ID                0.0
Transaction_Date           0.0
Transaction_Amount         0.0
Merchant_Category          0.0
Payment_Method             0.0
Device_Type                0.0
Location                   0.0
Is_International           0.0
Previous_Transactions      0.0
Average_Spend              0.0
Account_Age_Days           0.0
Suspicious_Keyword         0.0
Fraudulent                 0.0
Unnamed: 14              100.0
dtype: float64

In [9]:
missing_summary = pd.DataFrame({'Missing Values': df.isnull().sum(), 'Percentage': missing_percentage}) 
missing_summary

                       Missing Values  Percentage
Transaction_ID                      0         0.0
Customer_ID                         0         0.0
Transaction_Date                    0         0.0
Transaction_Amount                  0         0.0
Merchant_Category                   0         0.0
Payment_Method                      0         0.0
Device_Type                         0         0.0
Location                            0         0.0
Is_International                    0         0.0
Previous_Transactions               0         0.0
Average_Spend                       0         0.0
Account_Age_Days                    0         0.0
Suspicious_Keyword                  0         0.0
Fraudulent                          0         0.0
Unnamed: 14                      5000       100.0

In [10]:
# checking duplicate transactions in the dataset
duplicate_transactions = df.duplicated().sum()
print(f"Number of duplicate transactions: {duplicate_transactions}")

Number of duplicate transactions: 0

In [11]:
# checking duplicates exist in the dataset
df = df.drop_duplicates()
print(f"Shape after removing duplicates: {df.shape}")

Shape after removing duplicates: (5000, 15)

In [13]:
# checking columns names in dataset
df.columns.to_list()

['Transaction_ID',
 'Customer_ID',
 'Transaction_Date',
 'Transaction_Amount',
 'Merchant_Category',
 'Payment_Method',
 'Device_Type',
 'Location',
 'Is_International',
 'Previous_Transactions',
 'Average_Spend',
 'Account_Age_Days',
 'Suspicious_Keyword',
 'Fraudulent',
 'Unnamed: 14']

In [21]:
# removing unnecessary columns from the dataset
print(df['Unnamed: 14'].isnull().all())

True

In [22]:
# now we can remove the column 'Unnamed: 14' from the dataset as it contains all null values.
df = df.drop(['Unnamed: 14'], axis=1)

In [23]:
print(df.shape)
print(df.columns.tolist())

(5000, 14)
['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Transaction_Amount', 'Merchant_Category', 'Payment_Method', 'Device_Type', 'Location', 'Is_International', 'Previous_Transactions', 'Average_Spend', 'Account_Age_Days', 'Suspicious_Keyword', 'Fraudulent']

In [24]:
#check datatypes
print(df.dtypes)

Transaction_ID               str
Customer_ID                  str
Transaction_Date             str
Transaction_Amount       float64
Merchant_Category            str
Payment_Method               str
Device_Type                  str
Location                     str
Is_International           int64
Previous_Transactions      int64
Average_Spend            float64
Account_Age_Days           int64
Suspicious_Keyword           str
Fraudulent                 int64
dtype: object

In [27]:
df["Transaction_Date"]= pd.to_datetime(df["Transaction_Date"], format= "%d-%m-%Y %H:%M:%S", errors= "coerce")

In [28]:
print(df["Transaction_Date"].dtypes)

datetime64[s]

In [30]:
#checking for date conversion created problems
invalid_dates = df[df["Transaction_Date"].isnull()]
print("invalid_dates", invalid_dates)

invalid_dates      Transaction_ID Customer_ID Transaction_Date  Transaction_Amount  \
0           T100000    CUST3252              NaT               37.54
1           T100001    CUST1630              NaT              240.81
2           T100002    CUST7852              NaT              105.34
3           T100003    CUST4892              NaT               73.04
4           T100004    CUST8831              NaT               13.57
...             ...         ...              ...                 ...
4995        T104995    CUST3702              NaT              182.15
4996        T104996    CUST6007              NaT               10.17
4997        T104997    CUST6812              NaT               31.78
4998        T104998    CUST9120              NaT              135.31
4999        T104999    CUST1080              NaT               72.77

     Merchant_Category Payment_Method Device_Type   Location  \
0               Travel         PayPal         POS  Bengaluru
1            Utilities         PayPal      Mobile  Bengaluru
2        Entertainment     Debit Card      Mobile  Bengaluru
3            Utilities     NetBanking     Desktop    Kolkata
4            Utilities    Credit Card     Desktop  Bengaluru
...                ...            ...         ...        ...
4995       Electronics     Debit Card      Mobile    Kolkata
4996           Fashion    Credit Card     Desktop    Chennai
4997           Grocery     Debit Card      Mobile    Kolkata
4998         Utilities     Debit Card      Mobile  Bengaluru
4999     Entertainment            UPI      Mobile  Bengaluru

      Is_International  Previous_Transactions  Average_Spend  \
0                    0                     94         417.40
1                    0                     76         335.47
2                    0                     60         432.03
3                    0                     68         488.30
4                    0                     57         437.03
...                ...                    ...            ...
4995                 0                     13         277.99
4996                 0                    128         477.24
4997                 1                     76         442.62
4998                 0                     13          73.33
4999                 0                    146          30.23

      Account_Age_Days Suspicious_Keyword  Fraudulent
0                 1492                 No           0
1                   66                 No           0
2                  216                 No           0
3                  449                 No           0
4                  754                 No           0
...                ...                ...         ...
4995               840                 No           0
4996               441                 No           0
4997              1474                 No           1
4998               246                 No           0
4999               699                 No           0

[5000 rows x 14 columns]

In [31]:
# checking numeric columns in the dataset
numeric_columns = df.select_dtypes(include=[np.int64, np.float64]).columns.tolist()
print("Numeric columns:", numeric_columns)

Numeric columns: ['Transaction_Amount', 'Is_International', 'Previous_Transactions', 'Average_Spend', 'Account_Age_Days', 'Fraudulent']

In [32]:
df[numeric_columns].describe()

,Transaction_Amount,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Fraudulent
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,79.180664,0.088200,99.414000,258.377132,1011.158200,0.096400
std,78.964045,0.283614,57.022968,140.230639,568.633834,0.295169
min,0.000000,0.000000,1.000000,10.010000,30.000000,0.000000
25%,22.365000,0.000000,50.000000,138.772500,530.000000,0.000000
50%,55.455000,0.000000,100.000000,261.810000,1012.500000,0.000000
75%,110.297500,0.000000,148.000000,378.525000,1496.000000,0.000000
max,653.800000,1.000000,199.000000,499.990000,1999.000000,1.000000

In [37]:
# checking categorical columns in the dataset
categorical_columns = df.select_dtypes(include=[object]).columns
print(categorical_columns) 

for col in categorical_columns:
    print(f"Column: {col}")
    print(df[col].value_counts())
    print("\n")

C:\Users\umair\AppData\Local\Temp\ipykernel_18196\330384545.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=[object]).columns

Index(['Transaction_ID', 'Customer_ID', 'Merchant_Category', 'Payment_Method',
       'Device_Type', 'Location', 'Suspicious_Keyword'],
      dtype='str')
Column: Transaction_ID
Transaction_ID
T100000    1
T100001    1
T100002    1
T100003    1
T100004    1
          ..
T104995    1
T104996    1
T104997    1
T104998    1
T104999    1
Name: count, Length: 5000, dtype: int64


Column: Customer_ID
Customer_ID
CUST8944    5
CUST9322    4
CUST6465    4
CUST7707    4
CUST2246    4
           ..
CUST1077    1
CUST1920    1
CUST6812    1
CUST9120    1
CUST1080    1
Name: count, Length: 3847, dtype: int64


Column: Merchant_Category
Merchant_Category
Food             684
Electronics      650
Entertainment    630
Grocery          629
Fashion          608
Health           606
Travel           599
Utilities        594
Name: count, dtype: int64


Column: Payment_Method
Payment_Method
NetBanking     1037
PayPal         1022
Debit Card     1008
Credit Card     972
UPI             961
Name: count, dtype: int64


Column: Device_Type
Device_Type
Desktop    1679
POS        1673
Mobile     1648
Name: count, dtype: int64


Column: Location
Location
Delhi        758
Mumbai       741
Hyderabad    725
Pune         722
Kolkata      713
Bengaluru    686
Chennai      655
Name: count, dtype: int64


Column: Suspicious_Keyword
Suspicious_Keyword
No     4740
Yes     260
Name: count, dtype: int64

In [41]:
# checking the target for fraud detection in the dataset
print(df['Fraudulent'].value_counts())

print(df['Fraudulent'].value_counts(normalize=True) * 100)

Fraudulent
0    4518
1     482
Name: count, dtype: int64
Fraudulent
0    90.36
1     9.64
Name: proportion, dtype: float64

In [42]:
# checking for all null values, missing values, and duplicates in the dataset

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Rows: 5000
Columns: 14

Missing values:
Transaction_ID              0
Customer_ID                 0
Transaction_Date         5000
Transaction_Amount          0
Merchant_Category           0
Payment_Method              0
Device_Type                 0
Location                    0
Is_International            0
Previous_Transactions       0
Average_Spend               0
Account_Age_Days            0
Suspicious_Keyword          0
Fraudulent                  0
dtype: int64

Duplicate rows:
0

Data types:
Transaction_ID                     str
Customer_ID                        str
Transaction_Date         datetime64[s]
Transaction_Amount             float64
Merchant_Category                  str
Payment_Method                     str
Device_Type                        str
Location                           str
Is_International                 int64
Previous_Transactions            int64
Average_Spend                  float64
Account_Age_Days                 int64
Suspicious_Keyword                 str
Fraudulent                       int64
dtype: object

In [61]:
# creating a new csv file for cleaned dataset

output_path = "D:\\Fraud Detection model project 2\\Raw_dataset\\financial_fraud_detection_cleaned.csv"

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.